.section .text
.global context_switch

# a0 = &old->regs (Endereço do array da tarefa atual)
# a1 = &new->regs (Endereço do array da próxima tarefa)

context_switch:
  # Salva o contexto da tarefa que está saindo
  sd ra, 0(a0)
  sd sp, 8(a0)
  sd s0, 16(a0)
  sd s1, 24(a0)
  sd s2, 32(a0)
  sd s3, 40(a0)
  sd s4, 48(a0)
  sd s5, 56(a0)
  sd s6, 64(a0)
  sd s7, 72(a0)
  sd s8, 80(a0)
  sd s9, 88(a0)
  sd s10, 96(a0)
  sd s11, 104(a0)
  sd gp, 112(a0)
  sd tp, 120(a0)

  # Carrega o contexto da próxima tarefa
  ld ra, 0(a1)
  ld sp, 8(a1)
  ld s0, 16(a1)
  ld s1, 24(a1)
  ld s2, 32(a1)
  ld s3, 40(a1)
  ld s4, 48(a1)
  ld s5, 56(a1)
  ld s6, 64(a1)
  ld s7, 72(a1)
  ld s8, 80(a1)
  ld s9, 88(a1)
  ld s10, 96(a1)
  ld s11, 104(a1)
  ld gp, 112(a1)
  ld tp, 120(a1)

  ret